import { useState } from 'react'
import PlannerForm from './components/PlannerForm.jsx'
import MealPlan from './components/MealPlan.jsx'
import ShoppingList from './components/ShoppingList.jsx'
import LoadingState from './components/LoadingState.jsx'
import { generateMealPlan } from './lib/claude.js'
import { exportPlanToPdf } from './lib/pdf.js'

export default function App() {
  const [view, setView] = useState('form') // 'form' | 'loading' | 'plan'
  const [plan, setPlan] = useState(null)
  const [prefs, setPrefs] = useState(null)
  const [apiKey, setApiKey] = useState('')
  const [error, setError] = useState('')

  const runPlanner = async ({ apiKey: key, prefs: p }) => {
    setError('')
    setView('loading')
    setApiKey(key)
    setPrefs(p)
    try {
      const result = await generateMealPlan(key, p)
      setPlan(result)
      setView('plan')
    } catch (err) {
      console.error(err)
      setError(err.message || 'Something went wrong generating your meal plan.')
      setView('form')
    }
  }

  const regenerate = async () => {
    if (!prefs || !apiKey) return
    setView('loading')
    try {
      const result = await generateMealPlan(apiKey, prefs)
      setPlan(result)
      setView('plan')
    } catch (err) {
      setError(err.message)
      setView('plan')
    }
  }

  return (
    <div className="min-h-screen">
      <header className="no-print">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 pt-10 pb-6">
          <div className="flex items-center gap-3">
            <div className="h-12 w-12 rounded-2xl bg-sage-600 text-white flex items-center justify-center text-2xl shadow-sm">
              🥗
            </div>
            <div>
              <h1 className="text-3xl font-display font-bold text-sage-800 leading-tight">
                Weekly Meal Planner
              </h1>
              <p className="text-sage-600 text-sm">
                Personalized 7-day meal plans, generated by Claude.
              </p>
            </div>
          </div>
        </div>
      </header>

      <main className="max-w-5xl mx-auto px-4 sm:px-6 pb-20">
        {error && (
          <div className="no-print mb-4 rounded-xl border border-red-200 bg-red-50 text-red-800 px-4 py-3 text-sm">
            {error}
          </div>
        )}

        {view === 'form' && (
          <PlannerForm onSubmit={runPlanner} loading={false} />
        )}

        {view === 'loading' && <LoadingState />}

        {view === 'plan' && plan && (
          <div className="space-y-8">
            {/* Toolbar */}
            <div className="no-print flex flex-wrap items-center justify-between gap-3 card p-4">
              <div className="text-sage-700 text-sm">
                <span className="font-semibold">Your plan is ready.</span>{' '}
                Tap any meal to reveal its recipe.
              </div>
              <div className="flex gap-2">
                <button onClick={() => setView('form')} className="btn-secondary">
                  ← Edit preferences
                </button>
                <button onClick={regenerate} className="btn-secondary">
                  ↻ Regenerate
                </button>
                <button
                  onClick={() => exportPlanToPdf(plan, prefs)}
                  className="btn-accent"
                >
                  ⤓ Download PDF
                </button>
              </div>
            </div>

            {/* Summary */}
            <div className="card p-6">
              <h2 className="text-xl font-display font-semibold text-sage-800 mb-2">
                Your week at a glance
              </h2>
              <div className="flex flex-wrap gap-2 text-sm">
                {prefs.diets.map((d) => (
                  <span key={d} className="chip chip-on">{d}</span>
                ))}
                {[...prefs.allergies, ...(prefs.allergyOther ? [prefs.allergyOther] : [])]
                  .filter(Boolean)
                  .map((a) => (
                    <span key={a} className="chip bg-red-50 text-red-700 border-red-200">
                      No {a}
                    </span>
                  ))}
                {prefs.cuisines.map((c) => (
                  <span key={c} className="chip bg-orange-50 text-tangerine-600 border-orange-200">
                    {c}
                  </span>
                ))}
                <span className="chip bg-cream-100 text-amber-800 border-cream-200">
                  {prefs.servings} servings
                </span>
                <span className="chip bg-cream-100 text-amber-800 border-cream-200">
                  {prefs.cookingTime} cook time
                </span>
              </div>
            </div>

            <section>
              <h2 className="text-2xl font-display font-semibold text-sage-800 mb-4">
                7-day meal plan
              </h2>
              <MealPlan plan={plan} />
            </section>

            <section>
              <ShoppingList plan={plan} />
            </section>

            <div className="no-print flex justify-center pt-4">
              <button
                onClick={() => exportPlanToPdf(plan, prefs)}
                className="btn-primary text-lg"
              >
                ⤓ Download printable PDF
              </button>
            </div>
          </div>
        )}
      </main>

      <footer className="no-print text-center text-xs text-sage-500 pb-8">
        Made with Claude • Your data stays in your browser
      </footer>
    </div>
  )
}
